spring:
  jpa:
    generate-ddl: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa


aws:
  accessKey: ---
  secretKey: ---
  bucketName: my-test-bucket-vin